CSP-1506: Decline Account Request - Confirmation Page
SkillsFundingAgency/das-employer-pr-web pull request #30
Opened 2024-10-09 11:40 UTC by shaun-downey-education

- Added a new shutter page to handle the decline scenario when reviewing an AddAccount request.

2024-10-09 14:01 UTC, DevenKShah commented on src/SFA.DAS.Employer.PR.Web/Controllers/YourTrainingProvidersController.cs
> +        RequestAction requestActionEnum = (RequestAction)Enum.Parse(typeof(RequestAction), requestAction);
There is a generic `Enum.Parse<RequestAction>(requestAction)`

2024-10-09 14:09 UTC, DevenKShah requested changes

2024-10-09 14:09 UTC, DevenKShah commented on src/SFA.DAS.Employer.PR.Web/Controllers/DeclineAddAccountConfirmationController.cs
> +        );
This should be done in the POST action of the previous page, this should be simply showing the view

2024-10-09 14:13 UTC, DevenKShah reviewed
The changesaction should be carried out in the POST action instead of at redirection

2024-10-10 15:44 UTC, PeterDavidWilliams approved these changes, later dismissed

2024-10-11 12:28 UTC, PeterDavidWilliams approved these changes, later dismissed

2024-10-14 08:33 UTC, DevenKShah approved these changes, later dismissed

2024-10-15 15:02 UTC, PeterDavidWilliams approved these changes, later dismissed

2024-10-15 15:40 UTC, DevenKShah submitted a review, later dismissed

2024-10-17 09:15 UTC, DevenKShah approved these changes

2024-10-17 15:03 UTC, merged